name: PR 编译检查

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BYOND_MAJOR: 516
      BYOND_MINOR: 1673

    steps:
      - name: 获取含 PR 源码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          sudo apt-get install -y make gcc unzip libcurl4:i386

      - name: 下载 Byond
        run: |
          bash tools/ci/install_byond.sh

      - name: 编译源码
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          bash tools/build/build.sh
